## Метрики качества классификации

В этом практическом задании три обязательные и одна дополнительная задача.
<br>
*Обязательные задачи* нужно сделать для того, чтобы проверить, что вы действительно усвоили материал. Если у вас всё получилось, то можете переходить к следующей теме.
<br>
*Дополнительные задачи* для тех, кто хочет немного углубиться в тему и тщательнее поработать с матрицей ошибок.
<br>
Удачи!

Цели практического задания:


1.   Научиться рассчитывать метрику точности (Accuracy).
2.   Научиться рассчитывать и интерпретировать матрицу ошибок (confusion matrix).



---



---

## Обязательные задачи

1. *Размер тестовой выборки*

Загрузите файл с данными `practice3.csv`. В нём содержатся результаты обучения модели машинного обучения. Она предсказывает, продлит ли пользователь подписку на сервис в следующем месяце. Значение 0 — не продлит, 1 — продлит.

В колонке `true` находятся истинные значения целевой переменной (продлил ли пользователь подписку на самом деле).

В колонке `pred` — значения, предсказанные моделью (прогноз модели по пользователю).

В колонке `set_label` — к тренировочной или к тестовой выборке относится данное наблюдение.


Узнайте, сколько процентов данных составляет тестовая выборка от общего количества наблюдений.

In [21]:
# Здесь ваш код
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [5]:
df = pd.read_csv('/content/practice3.csv')
df

     true  pred set_label
0       1     1     train
1       1     1     train
2       1     1     train
3       1     1     train
4       1     1      test
..    ...   ...       ...
995     0     0     train
996     0     0     train
997     0     0     train
998     1     1      test
999     0     0     train

[1000 rows x 3 columns]

In [11]:
(df.set_label == 'test').sum() / len(df)

np.float64(0.33)

Тестовая выборка составляет 33% от общего количества наблюдений

2. *Точность модели*

На данных из предыдущего задания посчитайте точность модели на тестовой и тренировочной выборках.

In [20]:
# Здесь ваш код
df_test = df[df.set_label == 'test']
df_train = df[df.set_label == 'train']

print(f'Точность предсказания модели на тестовой выборке: {round(accuracy_score(df_test.true, df_test.pred), 2)}')
print(f'Точность предсказания модели на тренировочной выборке: {round(accuracy_score(df_train.true, df_train.pred), 3)}')

Точность предсказания модели на тестовой выборке: 0.72
Точность предсказания модели на тренировочной выборке: 1.0

Похоже модель переобучилась

3. *Матрица ошибок*

На данных из предыдущего задания выведите матрицу ошибок для предсказаний на тестовых данных. Интерпретируйте результат: какие особенные характеристики есть у полученной модели на тестовых данных?

In [22]:
# Здесь ваш код
confusion_matrix(df_test.true, df_test.pred)

array([[  0,  94],
       [  0, 236]])

In [23]:
confusion_matrix(df_train.true, df_train.pred)

array([[222,   0],
       [  0, 448]])

На тестовых  данных модель всегда предсказывает 1, и не выявляет 0

## Дополнительные задачи

Загрузите файл с данными `practice3_extra.csv`. В нём содержатся результаты обучения модели машинного обучения, которая предсказывает покупательскую способность клиента: 0 — низкая покупательская способность, 1 — средняя покупательская способность, 2 — высокая.

В колонке `true` находятся истинные значения целевой переменной (к какому классу покупательской способности на самом деле относится клиент).

В колонке `pred` — значения покупательской способности, предсказанные моделью.

Выведите матрицу ошибок и, исходя из её результатов, ответьте на следующие вопросы:
1. Сколько экземпляров класса 3 были предсказаны как класс 1?
2. Сколько экземпляров класса 2 были предсказаны как класс 3?
3. Какой класс модель угадывает хуже всего и почему?

In [25]:
df = pd.read_csv('/content/practice3_extra.csv')
df.head()

   true  pred
0     3     2
1     2     2
2     1     1
3     1     1
4     1     0

In [28]:
confusion_matrix(df.true, df.pred)

array([[161,   5,   4,   5],
       [  7, 147,   9,   6],
       [  6,   5, 164,   7],
       [  3,   6,   5, 160]])

In [31]:
df.true.value_counts() - df.pred.value_counts()

0   -2
1    6
2    0
3   -4
Name: count, dtype: int64



1.   6
2.   7
3.   Модель хуже угадывает 1 класс. Так как имеет 6 значений неправльно предсказанных, это больше всего по сравнению с другими моделями. Но также можно сказать что модель перееоцениват классы 0 и 3

Тут также может помочь метрика Recall. Она показывает, какую долю объектов положительного класса из всех объектов положительного класса нашёл алгоритм. https://en.wikipedia.org/wiki/Precision_and_recall


Чем больше значение метрики, тем больше объектов данного класса из всех его представителей было угадано. Вывести Recall для каждого класса можно с помощью функции `classification_report`.

In [27]:
from sklearn.metrics import classification_report
print(classification_report(df.true, df.pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.91       175
           1       0.90      0.87      0.89       169
           2       0.90      0.90      0.90       182
           3       0.90      0.92      0.91       174

    accuracy                           0.90       700
   macro avg       0.90      0.90      0.90       700
weighted avg       0.90      0.90      0.90       700